/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRequestRouteImport } from './routes/_app.request'
import { Route as AppNearbyRequestsRouteImport } from './routes/_app.nearby-requests'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppHospitalsRouteImport } from './routes/_app.hospitals'
import { Route as AppHospitalChainRouteImport } from './routes/_app.hospital-chain'
import { Route as AppHospitalRouteImport } from './routes/_app.hospital'
import { Route as AppHelpHospitalRouteImport } from './routes/_app.help-hospital'
import { Route as AppDonorsRouteImport } from './routes/_app.donors'
import { Route as AppDonorRouteImport } from './routes/_app.donor'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCertifyRouteImport } from './routes/_app.certify'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestRoute = AppRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => AppRoute,
} as any)
const AppNearbyRequestsRoute = AppNearbyRequestsRouteImport.update({
  id: '/nearby-requests',
  path: '/nearby-requests',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsRoute = AppHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalChainRoute = AppHospitalChainRouteImport.update({
  id: '/hospital-chain',
  path: '/hospital-chain',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalRoute = AppHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpHospitalRoute = AppHelpHospitalRouteImport.update({
  id: '/help-hospital',
  path: '/help-hospital',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorsRoute = AppDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AppRoute,
} as any)
const AppDonorRoute = AppDonorRouteImport.update({
  id: '/donor',
  path: '/donor',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCertifyRoute = AppCertifyRouteImport.update({
  id: '/certify',
  path: '/certify',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/certify': typeof AppCertifyRoute
  '/dashboard': typeof AppDashboardRoute
  '/donor': typeof AppDonorRoute
  '/donors': typeof AppDonorsRoute
  '/help-hospital': typeof AppHelpHospitalRoute
  '/hospital': typeof AppHospitalRoute
  '/hospital-chain': typeof AppHospitalChainRoute
  '/hospitals': typeof AppHospitalsRoute
  '/inventory': typeof AppInventoryRoute
  '/nearby-requests': typeof AppNearbyRequestsRoute
  '/request': typeof AppRequestRoute
  '/search': typeof AppSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/certify': typeof AppCertifyRoute
  '/dashboard': typeof AppDashboardRoute
  '/donor': typeof AppDonorRoute
  '/donors': typeof AppDonorsRoute
  '/help-hospital': typeof AppHelpHospitalRoute
  '/hospital': typeof AppHospitalRoute
  '/hospital-chain': typeof AppHospitalChainRoute
  '/hospitals': typeof AppHospitalsRoute
  '/inventory': typeof AppInventoryRoute
  '/nearby-requests': typeof AppNearbyRequestsRoute
  '/request': typeof AppRequestRoute
  '/search': typeof AppSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/certify': typeof AppCertifyRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/donor': typeof AppDonorRoute
  '/_app/donors': typeof AppDonorsRoute
  '/_app/help-hospital': typeof AppHelpHospitalRoute
  '/_app/hospital': typeof AppHospitalRoute
  '/_app/hospital-chain': typeof AppHospitalChainRoute
  '/_app/hospitals': typeof AppHospitalsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/nearby-requests': typeof AppNearbyRequestsRoute
  '/_app/request': typeof AppRequestRoute
  '/_app/search': typeof AppSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/certify'
    | '/dashboard'
    | '/donor'
    | '/donors'
    | '/help-hospital'
    | '/hospital'
    | '/hospital-chain'
    | '/hospitals'
    | '/inventory'
    | '/nearby-requests'
    | '/request'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/certify'
    | '/dashboard'
    | '/donor'
    | '/donors'
    | '/help-hospital'
    | '/hospital'
    | '/hospital-chain'
    | '/hospitals'
    | '/inventory'
    | '/nearby-requests'
    | '/request'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/certify'
    | '/_app/dashboard'
    | '/_app/donor'
    | '/_app/donors'
    | '/_app/help-hospital'
    | '/_app/hospital'
    | '/_app/hospital-chain'
    | '/_app/hospitals'
    | '/_app/inventory'
    | '/_app/nearby-requests'
    | '/_app/request'
    | '/_app/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/request': {
      id: '/_app/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof AppRequestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nearby-requests': {
      id: '/_app/nearby-requests'
      path: '/nearby-requests'
      fullPath: '/nearby-requests'
      preLoaderRoute: typeof AppNearbyRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospitals': {
      id: '/_app/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof AppHospitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospital-chain': {
      id: '/_app/hospital-chain'
      path: '/hospital-chain'
      fullPath: '/hospital-chain'
      preLoaderRoute: typeof AppHospitalChainRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hospital': {
      id: '/_app/hospital'
      path: '/hospital'
      fullPath: '/hospital'
      preLoaderRoute: typeof AppHospitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help-hospital': {
      id: '/_app/help-hospital'
      path: '/help-hospital'
      fullPath: '/help-hospital'
      preLoaderRoute: typeof AppHelpHospitalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donors': {
      id: '/_app/donors'
      path: '/donors'
      fullPath: '/donors'
      preLoaderRoute: typeof AppDonorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/donor': {
      id: '/_app/donor'
      path: '/donor'
      fullPath: '/donor'
      preLoaderRoute: typeof AppDonorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certify': {
      id: '/_app/certify'
      path: '/certify'
      fullPath: '/certify'
      preLoaderRoute: typeof AppCertifyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCertifyRoute: typeof AppCertifyRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonorRoute: typeof AppDonorRoute
  AppDonorsRoute: typeof AppDonorsRoute
  AppHelpHospitalRoute: typeof AppHelpHospitalRoute
  AppHospitalRoute: typeof AppHospitalRoute
  AppHospitalChainRoute: typeof AppHospitalChainRoute
  AppHospitalsRoute: typeof AppHospitalsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppNearbyRequestsRoute: typeof AppNearbyRequestsRoute
  AppRequestRoute: typeof AppRequestRoute
  AppSearchRoute: typeof AppSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCertifyRoute: AppCertifyRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDonorRoute: AppDonorRoute,
  AppDonorsRoute: AppDonorsRoute,
  AppHelpHospitalRoute: AppHelpHospitalRoute,
  AppHospitalRoute: AppHospitalRoute,
  AppHospitalChainRoute: AppHospitalChainRoute,
  AppHospitalsRoute: AppHospitalsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppNearbyRequestsRoute: AppNearbyRequestsRoute,
  AppRequestRoute: AppRequestRoute,
  AppSearchRoute: AppSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
